### ISSUE TITLE
More nicer design

### ISSUE THREAD

**Issue by ryonakano** [alexkdeveloper/dfc#5]
I prefer the design of ["desktop-file-creator"](https://github.com/alexkdeveloper/desktop-files-creator) that each labels for entries are in another line, open button in the header, etc.

![](https://raw.githubusercontent.com/alexkdeveloper/desktop-files-creator/main/data/screenshot.png)

BTW what is the differences between these two repositories? 😅

**Comment by alexkdeveloper** [comment]
Maybe it is better to prepare it for publication? Only the icons will need to be replaced here.

**Comment by alexkdeveloper** [comment]
You will also have to rename the files.

**Comment by alexkdeveloper** [comment]
If you like this interface, you can apply Orientation.VERTICAL to the Box container and rename it to vbox. We will have to work with the placement of the text label, since it will be placed in the center by default. Since the application will be distributed as a flatpack, it is not superfluous to think about the permissions in the manifest. The program works with only one directory, in which desktop files are stored. Maybe this permission will work: --filesystem=home/. local/share/applications?
The difference between repositories is that the first version has a built-in file editor, and this version does not have it, but you can simply open a folder with files and edit them in an external editor.

**Comment by alexkdeveloper** [comment]
Hi! I changed the application interface. Now it looks like in the image above. I changed the icons, changed the margins. You can see more details in the request.

**Comment by alexkdeveloper** [comment]
You can add image viewing to file_chooser for icons. Should I move the bottom button labeled "edit" to the window title?

**Comment by alexkdeveloper** [comment]
Added a preview of images for selecting icons.

**Comment by ryonakano** [comment]
Hmm, I expect the following behavior:
If users clicks Open button in the headerbar and the existing desktop file is opened, its content will be placed in the dedicated entries. And the label of the "Create" icon changes to "Edit".

**Comment by alexkdeveloper** [comment]
Maybe it's better to write "show all" instead of "edit"? Because when you click on the bottom button, a list of all the files in the application directory opens.
